"""empty message

Revision ID: 1b8aa8ba4968
Revises: a68ae7834d3f
Create Date: 2019-05-11 15:14:08.272043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8aa8ba4968'
down_revision = 'a68ae7834d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('question', sa.String(length=240, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('answer', sa.String(length=1024, collation='utf8mb4_general_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'user_payment', ['buyin_id', 'user_id'])
    op.add_column('buyins', sa.Column('price_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'buyins', 'prices', ['price_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'user_payment', ['buyin_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_payment', type_='unique')
    op.drop_table('help_item')

    op.drop_constraint(None, 'user_payment', type_='unique')
    op.drop_constraint(None, 'buyins', type_='foreignkey')
    op.drop_column('buyins', 'price_id')
    # ### end Alembic commands ###
