"""empty message

Revision ID: 2cb128744fb4
Revises: 
Create Date: 2019-04-14 11:08:16.209740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb128744fb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('PLANNING', 'OPEN', 'FIXED', 'ORDERED', 'FINISHED', name='states'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('next_step', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coffee_sorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120, collation='NOCASE'), nullable=True),
    sa.Column('email', sa.String(length=120, collation='NOCASE'), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('coffee_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coffee_type_id', sa.Integer(), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('price10', sa.Integer(), nullable=True),
    sa.Column('price25', sa.Integer(), nullable=True),
    sa.Column('price50', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_type_id'], ['coffee_sorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coffee_type_id', 'price_id')
    )
    op.create_table('individual_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('buyin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyin_id'], ['buyins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'buyin_id')
    )
    op.create_table('office_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('buyin_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['buyin_id'], ['buyins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'buyin_id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('coffee_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_type_id'], ['coffee_sorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['individual_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_rows')
    op.drop_table('user_roles')
    op.drop_table('office_orders')
    op.drop_table('individual_orders')
    op.drop_table('coffee_prices')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('prices')
    op.drop_table('coffee_sorts')
    op.drop_table('buyins')
    # ### end Alembic commands ###
