"""Orders

Revision ID: 5f0effdc5873
Revises: fc5878f41606
Create Date: 2019-03-09 13:01:56.452737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0effdc5873'
down_revision = 'fc5878f41606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coffee_prices')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_table('user_roles')
    op.drop_table('prices')
    op.drop_table('roles')
    op.drop_table('coffee_sorts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffee_sorts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('description', sa.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('prices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_from', sa.DATE(), nullable=False),
    sa.Column('date_to', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('email_confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=60), nullable=False),
    sa.CheckConstraint('active IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('coffee_prices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('coffee_type_id', sa.INTEGER(), nullable=False),
    sa.Column('price_id', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('price10', sa.INTEGER(), nullable=True),
    sa.Column('price25', sa.INTEGER(), nullable=True),
    sa.Column('price50', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_type_id'], ['coffee_sorts.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
