"""empty message

Revision ID: 8f422636540e
Revises: 
Create Date: 2019-05-05 01:26:58.573962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f422636540e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('PLANNING', 'OPEN', 'FIXED', 'ORDERED', 'FINISHED', name='states'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('next_step', sa.Date(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('shipment_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyins_state'), 'buyins', ['state'], unique=False)
    op.create_table('coffee_sorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('header', sa.String(length=120, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('content', sa.String(length=1024, collation='utf8mb4_general_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('email', sa.String(length=120, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('coffee_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coffee_type_id', sa.Integer(), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('price25', sa.Integer(), nullable=True),
    sa.Column('price50', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_type_id'], ['coffee_sorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coffee_type_id', 'price_id')
    )
    op.create_index(op.f('ix_coffee_prices_coffee_type_id'), 'coffee_prices', ['coffee_type_id'], unique=False)
    op.create_table('office_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyin_id', sa.Integer(), nullable=False),
    sa.Column('coffee_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyin_id'], ['buyins.id'], ),
    sa.ForeignKeyConstraint(['coffee_type_id'], ['coffee_sorts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyin_id', 'coffee_type_id')
    )
    op.create_index(op.f('ix_office_orders_buyin_id'), 'office_orders', ['buyin_id'], unique=False)
    op.create_index(op.f('ix_office_orders_coffee_type_id'), 'office_orders', ['coffee_type_id'], unique=False)
    op.create_table('office_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cups_per_day', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['buyin_id'], ['buyins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyin_id', 'user_id')
    )
    op.create_index(op.f('ix_office_rows_buyin_id'), 'office_rows', ['buyin_id'], unique=False)
    op.create_index(op.f('ix_office_rows_user_id'), 'office_rows', ['user_id'], unique=False)
    op.create_table('order_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coffee_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['buyin_id'], ['buyins.id'], ),
    sa.ForeignKeyConstraint(['coffee_type_id'], ['coffee_sorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyin_id', 'user_id', 'coffee_type_id')
    )
    op.create_index(op.f('ix_order_rows_buyin_id'), 'order_rows', ['buyin_id'], unique=False)
    op.create_index(op.f('ix_order_rows_coffee_type_id'), 'order_rows', ['coffee_type_id'], unique=False)
    op.create_index(op.f('ix_order_rows_user_id'), 'order_rows', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_viewed_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_viewed_news_news_id'), 'user_viewed_news', ['news_id'], unique=False)
    op.create_index(op.f('ix_user_viewed_news_user_id'), 'user_viewed_news', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_viewed_news_user_id'), table_name='user_viewed_news')
    op.drop_index(op.f('ix_user_viewed_news_news_id'), table_name='user_viewed_news')
    op.drop_table('user_viewed_news')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_order_rows_user_id'), table_name='order_rows')
    op.drop_index(op.f('ix_order_rows_coffee_type_id'), table_name='order_rows')
    op.drop_index(op.f('ix_order_rows_buyin_id'), table_name='order_rows')
    op.drop_table('order_rows')
    op.drop_index(op.f('ix_office_rows_user_id'), table_name='office_rows')
    op.drop_index(op.f('ix_office_rows_buyin_id'), table_name='office_rows')
    op.drop_table('office_rows')
    op.drop_index(op.f('ix_office_orders_coffee_type_id'), table_name='office_orders')
    op.drop_index(op.f('ix_office_orders_buyin_id'), table_name='office_orders')
    op.drop_table('office_orders')
    op.drop_index(op.f('ix_coffee_prices_coffee_type_id'), table_name='coffee_prices')
    op.drop_table('coffee_prices')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('prices')
    op.drop_table('news')
    op.drop_table('coffee_sorts')
    op.drop_index(op.f('ix_buyins_state'), table_name='buyins')
    op.drop_table('buyins')
    # ### end Alembic commands ###
