"""empty message

Revision ID: a68ae7834d3f
Revises: 8f422636540e
Create Date: 2019-05-05 12:43:05.622817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68ae7834d3f'
down_revision = '8f422636540e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('buyin_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['buyin_id'], ['buyins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_payment_buyin_id'), 'user_payment', ['buyin_id'], unique=False)
    op.create_index(op.f('ix_user_payment_user_id'), 'user_payment', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_payment_user_id'), table_name='user_payment')
    op.drop_index(op.f('ix_user_payment_buyin_id'), table_name='user_payment')
    op.drop_table('user_payment')
    # ### end Alembic commands ###
