"""empty message

Revision ID: dea1e7f776d2
Revises: a68ae7834d3f
Create Date: 2019-05-11 08:36:25.793247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea1e7f776d2'
down_revision = 'a68ae7834d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('question', sa.String(length=240, collation='NOCASE'), nullable=True),
    sa.Column('answer', sa.String(length=1024, collation='NOCASE'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'user_payment', ['buyin_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_payment', type_='unique')
    op.drop_table('help_item')
    # ### end Alembic commands ###
